######################################################################
# Automatically generated by qmake (3.0) Mon Feb 5 11:04:33 2018
######################################################################

QT += widgets
TEMPLATE = app
TARGET = qt-01
INCLUDEPATH += .

# Input
SOURCES += main.cpp
